BROKER_HOST: 66307877cde54201b7462d8941dcd49e.s1.eu.hivemq.cloud
BROKER_PORT: 8883
BROKER_TOPIC: ada502/weather
TOPIC_QOS: 1
CLIENT_ID: ada502mgdbfwd

MONGO_DB_CLUSTER: cluster0.woam8dg.mongodb.net
MONGODB_DATABASE_NAME: ada502testdb
MONGODB_COLLECTION_NAME: weatherdata

